import com.github.devlaq.shard.event.wrapper.EventTypes
import mindustry.game.EventType

object V6Registry {

    //Event mapping.
    val eventTriggerMapping = mapOf(
        EventType.Trigger.shock to EventTypes.Trigger.shock,
        EventType.Trigger.phaseDeflectHit to EventTypes.Trigger.phaseDeflectHit,
        EventType.Trigger.impactPower to EventTypes.Trigger.impactPower,
        EventType.Trigger.thoriumReactorOverheat to EventTypes.Trigger.thoriumReactorOverheat,
        EventType.Trigger.fireExtinguish to EventTypes.Trigger.fireExtinguish,
        EventType.Trigger.acceleratorUse to EventTypes.Trigger.acceleratorUse,
        EventType.Trigger.newGame to EventTypes.Trigger.newGame,
        EventType.Trigger.tutorialComplete to EventTypes.Trigger.tutorialComplete,
        EventType.Trigger.flameAmmo to EventTypes.Trigger.flameAmmo,
        EventType.Trigger.turretCool to EventTypes.Trigger.turretCool,
        EventType.Trigger.enablePixelation to EventTypes.Trigger.enablePixelation,
        EventType.Trigger.exclusionDeath to EventTypes.Trigger.exclusionDeath,
        EventType.Trigger.suicideBomb to EventTypes.Trigger.suicideBomb,
        EventType.Trigger.openWiki to EventTypes.Trigger.openWiki,
        EventType.Trigger.teamCoreDamage to EventTypes.Trigger.teamCoreDamage,
        EventType.Trigger.socketConfigChanged to EventTypes.Trigger.socketConfigChanged,
        EventType.Trigger.update to EventTypes.Trigger.update,
        EventType.Trigger.draw to EventTypes.Trigger.draw,
        EventType.Trigger.preDraw to EventTypes.Trigger.preDraw,
        EventType.Trigger.postDraw to EventTypes.Trigger.postDraw,
        EventType.Trigger.uiDrawBegin to EventTypes.Trigger.uiDrawBegin,
        EventType.Trigger.uiDrawEnd to EventTypes.Trigger.uiDrawEnd,
        EventType.Trigger.universeDrawBegin to EventTypes.Trigger.universeDrawBegin,
        EventType.Trigger.universeDraw to EventTypes.Trigger.universeDraw,
        EventType.Trigger.universeDrawEnd to EventTypes.Trigger.universeDrawEnd,
    )
    val eventMapping = mapOf(
        EventType.WinEvent::class.java to EventTypes.WinEvent::class.java,
        EventType.LoseEvent::class.java to EventTypes.LoseEvent::class.java,
        EventType.ResizeEvent::class.java to EventTypes.ResizeEvent::class.java,
        EventType.MapMakeEvent::class.java to EventTypes.MapMakeEvent::class.java,
        EventType.MapPublishEvent::class.java to EventTypes.MapPublishEvent::class.java,
        EventType.SaveLoadEvent::class.java to EventTypes.SaveLoadEvent::class.java,
        EventType.ClientCreateEvent::class.java to EventTypes.ClientCreateEvent::class.java,
        EventType.ServerLoadEvent::class.java to EventTypes.ServerLoadEvent::class.java,
        EventType.DisposeEvent::class.java to EventTypes.DisposeEvent::class.java,
        EventType.PlayEvent::class.java to EventTypes.PlayEvent::class.java,
        EventType.ResetEvent::class.java to EventTypes.ResetEvent::class.java,
        EventType.WaveEvent::class.java to EventTypes.WaveEvent::class.java,
        EventType.TurnEvent::class.java to EventTypes.TurnEvent::class.java,
        EventType.LineConfirmEvent::class.java to EventTypes.TurnEvent::class.java,
        EventType.TurretAmmoDeliverEvent::class.java to EventTypes.TurnEvent::class.java,
        EventType.CoreItemDeliverEvent::class.java to EventTypes.TurnEvent::class.java,
        EventType.BlockInfoEvent::class.java to EventTypes.TurnEvent::class.java,
        EventType.ContentInitEvent::class.java to EventTypes.ContentInitEvent::class.java,
        EventType.ClientLoadEvent::class.java to EventTypes.ClientLoadEvent::class.java,
        EventType.FileTreeInitEvent::class.java to EventTypes.FileTreeInitEvent::class.java,
        EventType.WorldLoadEvent::class.java to EventTypes.WorldLoadEvent::class.java,
        EventType.SectorLoseEvent::class.java to EventTypes.SectorLoseEvent::class.java,
        EventType.SectorInvasionEvent::class.java to EventTypes.SectorInvasionEvent::class.java,
        EventType.LaunchItemEvent::class.java to EventTypes.LaunchItemEvent::class.java,
        EventType.SectorLaunchEvent::class.java to EventTypes.SectorLaunchEvent::class.java,
        EventType.SchematicCreateEvent::class.java to EventTypes.SchematicCreateEvent::class.java,
        EventType.CommandIssueEvent::class.java to EventTypes.CommandIssueEvent::class.java,
        EventType.ClientPreConnectEvent::class.java to EventTypes.ClientPreConnectEvent::class.java,
        EventType.PlayerChatEvent::class.java to EventTypes.PlayerChatEvent::class.java,
        EventType.SectorCaptureEvent::class.java to EventTypes.SectorCaptureEvent::class.java,
        EventType.WithdrawEvent::class.java to EventTypes.WithdrawEvent::class.java,
        EventType.DepositEvent::class.java to EventTypes.DepositEvent::class.java,
        EventType.ConfigEvent::class.java to EventTypes.ConfigEvent::class.java,
        EventType.TapEvent::class.java to EventTypes.TapEvent::class.java,
        EventType.PickupEvent::class.java to EventTypes.PickupEvent::class.java,
        EventType.UnitControlEvent::class.java to EventTypes.UnitControlEvent::class.java,
        EventType.GameOverEvent::class.java to EventTypes.GameOverEvent::class.java,
        EventType.TileChangeEvent::class.java to EventTypes.TileChangeEvent::class.java,
        EventType.StateChangeEvent::class.java to EventTypes.StateChangeEvent::class.java,
        EventType.UnlockEvent::class.java to EventTypes.UnlockEvent::class.java,
        EventType.ResearchEvent::class.java to EventTypes.ResearchEvent::class.java,
        EventType.BlockBuildBeginEvent::class.java to EventTypes.BlockBuildBeginEvent::class.java,
        EventType.BlockBuildEndEvent::class.java to EventTypes.BlockBuildEndEvent::class.java,
        EventType.BuildSelectEvent::class.java to EventTypes.BuildSelectEvent::class.java,
        EventType.BlockDestroyEvent::class.java to EventTypes.BlockDestroyEvent::class.java,
        EventType.UnitDestroyEvent::class.java to EventTypes.UnitDestroyEvent::class.java,
        EventType.UnitDrownEvent::class.java to EventTypes.UnitDrownEvent::class.java,
        EventType.UnitCreateEvent::class.java to EventTypes.UnitCreateEvent::class.java,
        EventType.UnitUnloadEvent::class.java to EventTypes.UnitUnloadEvent::class.java,
        EventType.UnitChangeEvent::class.java to EventTypes.UnitChangeEvent::class.java,
        EventType.ConnectionEvent::class.java to EventTypes.ConnectionEvent::class.java,
        EventType.PlayerJoin::class.java to EventTypes.PlayerJoin::class.java,
        EventType.PlayerConnect::class.java to EventTypes.PlayerConnect::class.java,
        EventType.PlayerLeave::class.java to EventTypes.PlayerLeave::class.java,
        EventType.PlayerBanEvent::class.java to EventTypes.PlayerBanEvent::class.java,
        EventType.PlayerUnbanEvent::class.java to EventTypes.PlayerUnbanEvent::class.java,
        EventType.PlayerIpBanEvent::class.java to EventTypes.PlayerIpBanEvent::class.java,
        EventType.PlayerIpUnbanEvent::class.java to EventTypes.PlayerIpUnbanEvent::class.java,
    )

}